---
# Install AWS Plugin (see https://github.com/elasticsearch/elasticsearch-cloud-aws)
#
# The following variables need to be defined in your playbook or inventory:
# - elasticsearch_plugin_aws_version
#
# The following variables provide a for now limited configuration for the plugin.
# More options may be available in the future.
# (see http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-discovery-ec2.html):
# - elasticsearch_plugin_aws_ec2_groups
# - elasticsearch_plugin_aws_ec2_ping_timeout
# - elasticsearch_plugin_aws_access_key
# - elasticsearch_plugin_aws_secret_key
# - elasticsearch_plugin_aws_region

- name: aws | Removing AWS Plugin if it exists
  shell: bin/plugin --remove cloud-aws
    chdir={{ elasticsearch_home_dir }}
  when: elasticsearch_plugin_aws_reinstall is defined and elasticsearch_plugin_aws_reinstall == True
  ignore_errors: yes
- set_fact: elasticsearch_plugin_aws_url="elasticsearch/elasticsearch-cloud-aws/{{ elasticsearch_plugin_aws_version }}"
- set_fact: elasticsearch_plugin_aws_url="cloud-aws"
  when: "{{ elasticsearch_version | version_compare('2.0', '>=') }}"
- name: aws | Installing AWS Plugin
  shell: bin/plugin install {{ elasticsearch_plugin_aws_url }}
    chdir={{ elasticsearch_home_dir }}
  register: aws_plugins_installed
  changed_when: "'Installed' in aws_plugins_installed.stdout"
  failed_when: "aws_plugins_installed.rc != 0 and aws_plugins_installed.stdout.find('already exists. To update the plugin') == -1"
